const apiPaths = {
	aksjonspunkterPerEnhet: '/api/k9-los-api/avdelingsleder/nokkeltall/aksjonspunkter-per-enhet-historikk',
	allePaaVent: '/api/k9-los-api/avdelingsleder/nokkeltall/alle-paa-vent_v2',
	antallOppgaverIKoV3: (id: string) => `/api/k9-los-api/ny-oppgavestyring/ko/${id}/antall`,
	antallOppgaverIKoV3UtenReserverte: (id: string) =>
		`/api/k9-los-api/ny-oppgavestyring/ko/${id}/antall-uten-reserverte`,
	avdelinglederReservasjoner: '/api/k9-los-api/avdelingsleder/reservasjoner',
	endreReservasjoner: '/api/k9-los-api/saksbehandler/oppgaver/reservasjon/endre',
	forlengOppgavereservasjon: '/api/k9-los-api/saksbehandler/oppgaver/forleng',
	opphevReservasjoner: '/api/k9-los-api/saksbehandler/oppgaver/opphev',
	behandlede: '/api/k9-los-api/saksbehandler/oppgaver/behandlede',
	dagensTall: '/api/k9-los-api/avdelingsleder/nokkeltall/dagens-tall',
	driftsmeldinger: '/api/k9-los-api/driftsmeldinger',
	lagreDriftsmelding: '/api/k9-los-api/driftsmeldinger',
	slettDriftsmelding: '/api/k9-los-api/driftsmeldinger/slett',
	toggleDriftsmelding: '/api/k9-los-api/driftsmeldinger/toggle',
	hentAlleKoerSaksbehandlerV1: '/api/k9-los-api/saksbehandler/oppgaveko',
	hentAlleKoerSaksbehandlerV3: '/api/k9-los-api/ny-oppgavestyring/ko/saksbehandlerskoer',
	hentAndreSaksbehandleresKøerV3: '/api/k9-los-api/ny-oppgavestyring/ko/andre-saksbehandleres-koer',
	hentAvdelingslederStatus: '/api/k9-los-api/ny-oppgavestyring/nokkeltall/status',
	hentAvdelingslederStatusFordeling: '/api/k9-los-api/ny-oppgavestyring/nokkeltall/statusfordeling',
	hentDagensTall: '/api/k9-los-api/ny-oppgavestyring/nokkeltall/dagens-tall',
	hentFerdigstiltePerEnhet: '/api/k9-los-api/ny-oppgavestyring/nokkeltall/ferdigstilte-per-enhet',
	hentFelter: '/api/k9-los-api/ny-oppgavestyring/oppgave/felter',
	hentNyeOgFerdigstilteSisteSyvDager: (gruppe: string) =>
		`/api/k9-los-api/ny-oppgavestyring/nye-og-ferdigstilte?gruppe=${gruppe}`,
	hentOppgaveFelter: '/api/k9-los-api/ny-oppgavestyring/oppgave/felter',
	hentOppgaveFraKoV3: (id: string) => `/api/k9-los-api/ny-oppgavestyring/ko/${id}/fa-oppgave`,
	hentOppgaveko: (id: string) => `/api/k9-los-api/ny-oppgavestyring/ko/${id}`,
	hentOppgavekoer: '/api/k9-los-api/ny-oppgavestyring/ko/',
	hentOppgaver: '/api/k9-los-api/ny-oppgavestyring/oppgave/query',
	hentAntallOppgaver: '/api/k9-los-api/ny-oppgavestyring/oppgave/query/antall',
	hentOppgaverSomFil: '/api/k9-los-api/ny-oppgavestyring/oppgave/queryToFile',
	hentSaksbehandlereAvdelingsleder: '/api/k9-los-api/avdelingsleder/saksbehandlere',
	leggTilSaksbehandlerAvdelingsleder: '/api/k9-los-api/avdelingsleder/saksbehandlere/legg-til',
	hentSaksbehandlereSomSaksbehandler: '/api/k9-los-api/saksbehandler/oppgaver/saksbehandlere',
	hentSaksbehandlereIKoV3: (id: string) => `/api/k9-los-api/ny-oppgavestyring/ko/${id}/saksbehandlere`,
	hentTiNesteIKoV3: (id: string) => `/api/k9-los-api/ny-oppgavestyring/ko/${id}/oppgaver`,
	kodeverk: '/api/k9-los-api/kodeverk',
	kopierOppgaveko: '/api/k9-los-api/ny-oppgavestyring/ko/kopier',
	legacyOppgaveKoer: '/api/k9-los-api/avdelingsleder/oppgavekoer',
	leggTilSaksbehandler: '/api/k9-los-api/ny-oppgavestyring/ko/saksbehandler',
	nyeFerdigstilteOppsummering: '/api/k9-los-api/avdelingsleder/nokkeltall/nye-ferdigstilte-oppsummering',
	oppdaterOppgaveko: '/api/k9-los-api/ny-oppgavestyring/ko',
	oppgaver: '/api/k9-los-api/saksbehandler/oppgaver/antall',
	oppgaverAntallTotalt: '/api/k9-los-api/avdelingsleder/oppgaver/antall-totalt',
	opprettOppgaveko: '/api/k9-los-api/ny-oppgavestyring/ko/opprett',
	reserverOppgave: '/api/k9-los-api/saksbehandler/oppgaver/reserver',
	saksbehandler: '/api/k9-los-api/saksbehandler',
	saksbehandlerNesteOppgaver: (id: string) => `/api/k9-los-api/saksbehandler/oppgaver?id=${id}`,
	saksbehandlerReservasjoner: '/api/k9-los-api/saksbehandler/oppgaver/reserverte',
	hentAktivReservasjonForOppgave: '/api/k9-los-api/saksbehandler/oppgaver/aktiv-reservasjon',
	saksbehandlereIOppgaveko: '/api/k9-los-api/saksbehandler/oppgaveko/saksbehandlere',
	slettOppgaveko: '/api/k9-los-api/ny-oppgavestyring/ko/',
	slettSaksbehandler: '/api/k9-los-api/avdelingsleder/saksbehandlere/slett',
	sisteOppgaver: '/api/k9-los-api/ny-oppgavestyring/siste-oppgaver',
	sokV3: '/api/k9-los-api/ny-oppgavestyring/sok',
	validerQuery: '/api/k9-los-api/ny-oppgavestyring/oppgave/validate',
	hentLagredeSøk: '/api/k9-los-api/ny-oppgavestyring/lagret-sok',
	opprettLagretSøk: '/api/k9-los-api/ny-oppgavestyring/lagret-sok/opprett',
	endreLagretSøk: (id: string) => `/api/k9-los-api/ny-oppgavestyring/lagret-sok/${id}/endre`,
	kopierLagretSøk: (id: string) => `/api/k9-los-api/ny-oppgavestyring/lagret-sok/${id}/kopier`,
	slettLagretSøk: (id: string) => `/api/k9-los-api/ny-oppgavestyring/lagret-sok/${id}/slett`,
	hentAntallLagretSøk: (id: string) => `/api/k9-los-api/ny-oppgavestyring/lagret-sok/${id}/antall`,
	hentUttrekk: '/api/k9-los-api/ny-oppgavestyring/uttrekk',
	hentUttrekkForLagretSøk: (lagretSokId: string) =>
		`/api/k9-los-api/ny-oppgavestyring/uttrekk/lagret-sok/${lagretSokId}`,
	opprettUttrekk: '/api/k9-los-api/ny-oppgavestyring/uttrekk/opprett',
	slettUttrekk: (id: string) => `/api/k9-los-api/ny-oppgavestyring/uttrekk/${id}/slett`,
};

export default apiPaths;
