apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: k9-los-web
  namespace: k9saksbehandling
  labels:
    team: k9saksbehandling
spec:
  image: {{ image }}
  port: 8030
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: {{ azureTenant }}
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
      - /health/**
      - /logout
  liveness:
    path: health/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: health/isReady
    initialDelay: 20
    timeout: 1
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  accessPolicy:
    outbound:
      external:
      {{#each outboundExternalHosts as |host|}}
       - host: {{host}}
      {{/each}}
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 200m
      memory: 32Mi
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  env:
    - name: PROXY_CONFIG
      value: '{"apis":[
              {{#each proxyRedirects}}
                {"path":"{{path}}", "url":"{{url}}", "scopes":"{{scope}}", "backendPath":"{{backendPath}}"}{{#unless @last}},{{/unless}}
              {{/each}}
              ]}'
  {{#each env}}
    - name: {{this.name }}
      value: {{this.value}}
  {{/each}}