ingresses:
  - "https://k9-los-web.intern.nav.no"
azureTenant: nav.no
outboundExternalHosts:
  - k9-los-api.prod-fss-pub.nais.io
proxyRedirects:
  - path: "/api/k9-los-api"
    scope: "api://prod-fss.k9saksbehandling.k9-los-api/.default"
    url: "https://k9-los-api.prod-fss-pub.nais.io"
    backendPath: "/api"
  - path: "/api/forvaltning"
    scope: "api://prod-fss.k9saksbehandling.k9-los-api/.default"
    url: "https://k9-los-api.prod-fss-pub.nais.io"
    backendPath: "/forvaltning"
  - path: "/api/endringslogg"
    url: "https://familie-endringslogg.intern.nav.no"
resources:
  limits:
    memory: 200Mi
  requests:
    cpu: 50m
    memory: 100Mi
observability:
  autoInstrumentation:
    enabled: true
    runtime: nodejs
    destinations:
      - id: "grafana-lgtm"
  logging:
    destinations:
      - id: loki
      - id: elastic
