ingresses:
  - "https://k9-los-web.intern.nav.no"
azureTenant: nav.no
outboundExternalHosts:
  - k9-los-api.prod-fss-pub.nais.io
proxyRedirects:
  - path: "/api/k9-los-api"
    scope: "api://prod-fss.k9saksbehandling.k9-los-api/.default"
    url: "https://k9-los-api.prod-fss-pub.nais.io"
    backendPath: "/api"

env:
  - name: SAKSBEHANDLER_KAN_VELGE_NYE_KOER
    value: "true"
  - name: AVDELINGSLEDER_TILGANG_TIL_NYE_KOER
    value: "true"
