ingresses:
  - "https://k9-los-web.dev.adeo.no"
  - "https://k9-los-web.dev-fss.nais.io"
env:
  - name: K9_LOS_API_URL
    value: "http://k9-los-oidc-auth-proxy/api/k9-los-api"
  - name: APPLICATION_BASE_URL
    value: "https://k9-los-web.dev.adeo.no"
  - name: AUTH_PROXY_BASE_URL
    value: "https://k9-los-oidc-auth-proxy.dev.intern.nav.no"
  - name: AUTH_PROXY_BASE_URL_WSS
    value: "wss://k9-los-oidc-auth-proxy.dev.intern.nav.no"
  - name: LOGIN_REDIRECT_URL
    value: "http://k9-los-oidc-auth-proxy/login?redirect_uri=https://k9-los-web.dev.adeo.no/"
  - name: SAKSBEHANDLER_KAN_VELGE_NYE_KOER
    value: "enabled"
  - name: AVDELINGSLEDER_TILGANG_TIL_NYE_KOER
    value: "enabled"
