ingresses:
  - "https://k9-los-web.nais.adeo.no"
  - "https://k9-los-web.prod-fss.nais.io"
env:
  - name: OIDC_PROXY_URL
    value: "https://k9-los-oidc-auth-proxy.intern.nav.no/api/k9-los-api"
  - name: APPLICATION_BASE_URL
    value: "https://k9-los-web.nais.adeo.no"
  - name: AUTH_PROXY_BASE_URL
    value: "https://k9-los-oidc-auth-proxy.intern.nav.no"
  - name: AUTH_PROXY_BASE_URL_WSS
    value: "wss://k9-los-oidc-auth-proxy.intern.nav.no"
  - name: LOGIN_REDIRECT_URL
    value: "https://k9-los-oidc-auth-proxy.intern.nav.no/login?redirect_uri=https://k9-los-web.nais.adeo.no/"
  - name: SAKSBEHANDLER_KAN_VELGE_NYE_KOER
    value: "disabled"
  - name: AVDELINGSLEDER_TILGANG_TIL_NYE_KOER
    value: "disabled"
