name: Reusable k9-los-oidc-auth-proxy deployment
on:
  workflow_call:
    inputs:
      cluster:
        required: true
        type: string
      vars:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Hente kode
        uses: actions/checkout@v4
      - name: Deploy to cluster
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: ${{ inputs.cluster }}
          RESOURCE: nais/proxy/k9-los-oidc-auth-proxy.yml
          VARS: ${{ inputs.vars }}
