name: Deploy til preprod

on: [workflow_dispatch]

env:
  IMAGE_BASE_CR: ghcr.io/${{ github.repository }}
  GITHUB_USERNAME: x-access-token
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deploy-dev:
    name: Deploye til DEV
    runs-on: ubuntu-latest
    steps:
      - name: Hente kode
        uses: actions/checkout@v3
      - name: Sette yarn-config
        run: |
          yarn config set npmScopes.navikt.npmRegistryServer "https://npm.pkg.github.com"
          yarn config set npmScopes.navikt.npmAlwaysAuth true
          yarn config set npmScopes.navikt.npmAuthToken $NPM_AUTH_TOKEN
        env:
          NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Sette opp Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18.x
          cache: yarn
      - name: Installere moduler
        run: yarn install --immutable
      - name: Tester
        run: yarn test --maxWorkers=2
      - name: Linting
        run: yarn css:lint
      - name: Install Playwright Browsers
        run: yarn playwright install chromium
      - name: Run Playwright tests
        run: yarn playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Bygge kode
        run: yarn build
        env:
          SAKSBEHANDLER_KAN_VELGE_NYE_KOER: 'disabled'
          AVDELINGSLEDER_TILGANG_TIL_NYE_KOER: 'enabled'
      - name: Opprett release med Sentry
        run: yarn sentry-release
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      - name: Sette Docker-navn og -tag
        run: |
          echo "TAG=$(date +"%Y%m%d%H%M%S")-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Bygg og laste opp docker-image
        run: |
          echo "IMAGE=$IMAGE_BASE_CR:$TAG" >> $GITHUB_ENV
          docker pull node:alpine
          docker build --tag ${IMAGE_BASE_CR}:${TAG} --tag ${IMAGE_BASE_CR}:latest .
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u "x-access-token" --password-stdin ghcr.io
          docker push ${IMAGE_BASE_CR} --all-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploye til dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.DEPLOY_KEY }}
          CLUSTER: dev-fss
          RESOURCE: nais/frontend/k9-los-web.yml
          VARS: nais/frontend/dev.yml
