name: Last opp Docker image e2e
on:
  push:
    branches:
      - master
    paths:
      - 'e2e/**'
      - '.github/workflows/e2e-docker-image.yml'
env:
  IMAGE_BASE: ghcr.io/navikt/k9-los-web-e2e
jobs:
  push-docker-image:
    name: Push Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Hente kode
        uses: actions/checkout@v4
      - name: Sette Docker-navn og -tag
        run: |
          echo "IMAGE=$IMAGE_BASE:$(date +"%Y%m%d%H%M%S")-$(echo $GITHUB_SHA | cut -c1-7)">> $GITHUB_ENV
      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          tag: 'latest'
          team: k9saksbehandling
          pull: true
          dockerfile: ./e2e/Dockerfile
          docker_context: './e2e'
          image_suffix: 'e2e'
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
  verdikjede-tester:
    name: Verdikjedetester
    needs: [push-docker-image]
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      packages: read
    uses: navikt/sif-gha-workflows/.github/workflows/verdikjede-test-v2.yml@main
    with:
      tag: 'latest'
      suites: 'frontend-los'
      image_version: 'latest'
