name: Valider pull request
on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - 'LICENCE'
      - 'CODEOWNERS'
      - 'dev/**'
      - '**.yml'
      - '**.yaml'

jobs:
  valid-pull-request:
    name: Valider pull request
    runs-on: ubuntu-latest
    steps:
      - name: Hente kode
        uses: actions/checkout@v3

      - name: Sette opp Node
        uses: actions/setup-node@v3.5.0
        with:
          node-version: 16.x
          registry-url: https://npm.pkg.github.com/
          scope: '@navikt'
          cache: 'yarn'
      - name: Installere dependencies
        run: yarn install --ignore-optional --no-progress --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN  }}
      - name: Tester
        run: yarn test --maxWorkers=2
      - name: Linting
        run: yarn less:lint
      - name: Bygge
        run: yarn build
