name: Valider pull request
on:
  pull_request:
    branches-ignore:
      - slette_V1
    types: [opened, synchronize]
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - 'CODEOWNERS'

jobs:
  build-and-test:
    name: Bygg og test kode
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: read
    outputs:
      image_artifact_name: ${{ steps.docker-push.outputs.image-artifact-name }}
      image_version: ${{ github.sha }}

    steps:
      - name: Hente kode
        uses: actions/checkout@v6
      - name: Sette opp pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0
      - name: Sette opp Node
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: pnpm
      - name: Sette opp npm-auth mot GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Installere dependencies
        run: pnpm install --frozen-lockfile
      - name: Tester
        run: pnpm test --maxWorkers=2
      - name: Bygge
        run: pnpm build
      - name: Bygg Dockerimage
        uses: navikt/sif-gha-workflows/.github/actions/maven/build-push-docker-image@main # ratchet:exclude
        id: docker-push
        if: ${{github.actor != 'dependabot[bot]'}}
        with:
          build-version: ${{ github.sha }}
          push-image: 'false'
          upload-image: 'true'
          docker_platforms: 'linux/amd64'
          without_navikt_prefix: 'true'

          
  sif-code-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: navikt/sif-gha-workflows/.github/actions/sif-code-scan@v1


  verdikjede-tester:
    name: Verdikjedetester
    needs: [build-and-test]
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      packages: read
    uses: navikt/sif-gha-workflows/.github/workflows/verdikjede-test-v2.yml@main
    if: ${{github.actor != 'dependabot[bot]'}}
    with:
      suites: 'frontend-los'
      tag: ${{ needs.build-and-test.outputs.image_version }}
      image_version: ${{ needs.build-and-test.outputs.image_version }}
      override_image_artifact_name: ${{ needs.build-and-test.outputs.image_artifact_name }}
