name: Valider pull request
on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - 'CODEOWNERS'

jobs:
  valid-pull-request:
    name: Valider pull request
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: read
    steps:
      - name: Hente kode
        uses: actions/checkout@v4
      - name: Sette yarn-config
        run: |
          yarn config set npmScopes.navikt.npmRegistryServer "https://npm.pkg.github.com"
          yarn config set npmScopes.navikt.npmAlwaysAuth true
          yarn config set npmScopes.navikt.npmAuthToken $NPM_AUTH_TOKEN
        env:
          NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Sette opp Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: yarn
      - name: Installere dependencies
        run: yarn install --immutable
      - name: CSS lint
        run: yarn css:lint
      - name: Tester
        run: yarn test --maxWorkers=2
      - name: Bygge
        run: yarn build
      - name: Bygg Dockerimage
        uses: navikt/sif-gha-workflows/.github/actions/maven/build-push-docker-image@main # ratchet:exclude
        with:
          build-version: ${{ github.sha }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          namespace: ${{ inputs.namespace }}
          push-image: 'false'
          upload-image: 'true'
      - name: Kjør verdikjedetester
        uses: navikt/sif-gha-workflows/.github/workflows/verdikjede-test-v2.yml@main
        with:
          tag: ${{ needs.build-and-deploy.outputs.image_version }}
          suites: 'frontend-los'
          image_version: ${{ needs.build-and-deploy.outputs.image_version}}
