name: Valider pull request
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.MD"
      - ".gitignore"
      - "LICENCE"
      - "CODEOWNERS"
      - "dev/**"
      - "**.yml"
      - "**.yaml"

jobs:
  valid-pull-request:
    name: Valider pull request
    runs-on: ubuntu-latest
    steps:
      - name: Hente kode
        uses: actions/checkout@v3
      - name: Sette yarn-config
        run: |
          yarn config set npmScopes.navikt.npmRegistryServer "https://npm.pkg.github.com"
          yarn config set npmScopes.navikt.npmAlwaysAuth true
          yarn config set npmScopes.navikt.npmAuthToken $NPM_AUTH_TOKEN
        env:
          NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Sette opp Node
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 18.x
          cache: yarn
      - name: Installere dependencies
        run: yarn install --immutable
      - name: Tester
        run: yarn test --maxWorkers=2
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
      - name: Run Playwright tests
        run: yarn playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Linting
        run: yarn css:lint
      - name: Bygge
        run: yarn build
